### PR TITLE
[176883831] move global sdfs to OGIT

### PR DESCRIPTION
**Pull request by KaushikGondaliya**

### CODE REVIEW

**Comment by jane-doe** [comment]
Can one of the admins verify this patch?

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Comment by KaushikGondaliya** [comment]
test

**Review by viteke — APPROVED** [review]
Ok

**Pull request merged**
