### PR TITLE
HIRO Dev Portal Ontology Update

### PR DESCRIPTION
**Pull request by miraage**
+ Software.ApplicationReview vertex
+ Auth.Account -> creates -> Software.ApplicationReview
+ Software.ApplicationReview -> reviews -> Software.Application
+ Software.Application -> versions -> Software.Application

### CODE REVIEW

**Comment by miraage** [comment]
Hello @rudi147. Please review.

/cc @qasimikram

**Comment by qasimikram** [comment]
@miraage text format is not consistent.

**Comment by miraage** [comment]
.editorconfig would solve that.... :)

**Comment by cy303** [comment]
is it just me or is 

> Software.ApplicationReview -> responds -> Software.Application

a semantically rather strange construct? I would understand "review" or "rates" but "responds"?

**Comment by miraage** [comment]
@cy303 I was not certain about this particular edge. Which one of `reviews` or `rates` you think fits most?

**Comment by river-fall** [comment]
test

**Comment by cy303** [comment]
@miraage not completely sure either, I think it depends on the actual content of the ApplicationReview nodes... it has mandatory title and status and an optional comment.... what is the status field supposed to contain? if it's a plain numerical value, I'd probably go for "rates", if it is a free text field it might actually be "describes" or "reviews"... I guess as a rule of thumb it should be the verb which best fits in the sentence "an application review ..... an application" which in turn best describes what kind of data is in the review :)

**Comment by cy303** [comment]
which btw hints at "ogit/status" not being a good fit for the review content either ;)

**Comment by miraage** [comment]
@cy303 status stands for either `accepted` or `rejected`. I assume there are may be other status values in the future.

**Comment by miraage** [comment]
@fotto should we use ogit/Auth/Application here?

**Pull request merged**
