### PR TITLE
Make id attribute optional

### PR DESCRIPTION
**Pull request by stravlos**

### CODE REVIEW

**Comment by fabianmeyer** [comment]
That's quite an extensive change. Could you please elaborate?

**Comment by r0ckarong** [comment]
Was there some result to the request for clarification (https://github.com/arago/OGIT/pull/314#issuecomment-327467182)? If so could you please document the reason here so that it's not hidden away in heads?

**Comment by stravlos** [comment]
It was a misunderstanding

**Comment by fabianmeyer** [comment]
I thought the change was on "ogit/Node" instead of the actual "ogit/License"

**Pull request merged**
