### PR TITLE
TabTab Entities/Changes

### PR DESCRIPTION
**Pull request by thechriswalker**
@conofre here's the new pull request, amended now the master branch as changed.

Please comment if you have questions :smile:

### CODE REVIEW

**Comment by conofre** [comment]
@plarem 
Parent - ogit/Node - should tabtab change this in their pull request or will this be included within our changes to all entities parents?

Should the OGIT elements be placed in ogit/Forum NTO or in SGO?
entity Notification (SGO)
verbs moderates (SGO), wins (SGO), mentions (Forum)

Tks.

**Comment by thechriswalker** [comment]
I am happy to change the `parent` attribute, and to move items around between `NTO/Forum` and `SGO` as you see fit.

**Comment by conofre** [comment]
Hi @thechriswalker about attributes.any = true - it's not needed, as this is done per default.
About the parent attribute, let's wait for the feedback from @plarem to confirm how would be more practical to him, since he's doing changes related to this right now.
@plarem please check my previous comment and provide feedback.

**Comment by plarem** [comment]
1.
Inheritance will be removed, but for now please still write "parent: http://www.purl.org/ogit/Node" in every entity. Same for the free attributes. Now, all entities will be allowed to have free attributes but maybe graphit cannot handle this yet. So please use "any: true". I will talk to Stefan and will remove these attributes from all yaml files then when graphit can handle this.

2.
Should the OGIT elements be placed in ogit/Forum NTO or in SGO?
entity Notification (SGO)
verbs moderates (SGO), wins (SGO), mentions (Forum)

thats ok

**Comment by conofre** [comment]
@thechriswalker does moving the mentioned entitiy and verbs to SGO and Forum according to Peter's/my proposals sound good to you?
I'm checking with colleagues the KnowledgeItem entity and will get back to you about this.
All the rest is already discussed in previous comments :-)

**Comment by thechriswalker** [comment]
I have updated this pull request to take into account repo changes and also the requests above.

I have remove the extra KnowledgeItem entity as we will manage that in app, perhaps later with some help from GraphIT (pending outcome of https://itautopilot.atlassian.net/browse/GRA-72)

**Pull request merged**
