### PR TITLE
Add connection between ogit/Person -> ogit/Forum/Profile

### PR DESCRIPTION
**Pull request by bpneal**

### CODE REVIEW

**Comment by fabianmeyer** [comment]
Hi, what's the actual meaning of this relation? Shouldn't a 
"ogit/Forum/Profile - ogit/belongs -> ogit/Person"
or 
"ogit/Person - ogit/owns -> ogit/Forum/Profile"
?

**Comment by bpneal** [comment]
@fabianmeyer my thought was a `Person` `uses` a `Profile`, but would be happy to change to belongs. Will change PR now

**Comment by bpneal** [comment]
@fabianmeyer I have changed and pushed. I'm now using `belongs`

**Comment by bpneal** [comment]
Corresponds to Infrastructure Pull Request https://github.com/arago/infrastructure/pull/26

**Comment by fabianmeyer** [comment]
Thanks for the change! But doesn't a "Profile belongs to a Person" rather than a "Person belongs to a Profile"?

**Comment by bpneal** [comment]
@fabianmeyer I took my example from the previous description:

```
    ogit:from ogit:Organization;
    ogit:to ogit:Alert;
```
but agree that the other way would be more semantically correct.

Thanks

**Comment by bpneal** [comment]
Changed and pushed

**Pull request merged**
