### PR TITLE
Added new ogit types for 'Bluebird' project

### PR DESCRIPTION
**Pull request by ArturShoba**
@p1tz, please review
P.S.
I've attached visual representation of scheme
wp_20160815_17_12_55_pro

and [link to the ticket](https://itautopilot.atlassian.net/browse/AF-2158)

### CODE REVIEW

**Comment by viteke** [comment]
Please move it in a NTO

**Comment by ArturShoba** [comment]
I've moved to NTO (folder Bluebird). Please, review again.

**Comment by ArturShoba** [comment]
I've removed Bluebird folder and moved entities to BusinessProcess. Please, review again.

**Comment by ArturShoba** [comment]
Hi, @p1tz!
I've added new field 'enumValues' for saving questions (in json) to 'Survey' entity and renamed SurveyReply to SurveyCycle since it is more suitable name for tracking actions with surveys.

**Pull request merged**
