### PR TITLE
Change edge types

### PR DESCRIPTION
**Pull request by lroeser**
change edge type to Restrict issue traversal

### CODE REVIEW

**Comment by jane-doe** [comment]
Can one of the admins verify this patch?

**Review by cy303 — CHANGES_REQUESTED** [review]
Sorry this makes legal edges illegal, that's an absolute no-go

**Comment by lroeser** [comment]
no worries - Dentsu is the only customer using this namespace and i will clean up once merged.

**Comment by cy303** [comment]
> no worries - Dentsu is the only customer using this namespace and i will clean up once merged.

Once merged, the graph will have illegal stuff in it that it can not even validate and I wouldn't even count on being able to clean certain things up. You can _add_ edge definitions all you want but _deleting_ them is a no-go operation in ogit. Write-Only, no undo. Not going to discuss this. If you don't want to use "uses" here anymore, fine by me, don't use it - try to delete stuff from the ontology and I will raise a red flag anytime for anything as it might f**k up internal consistencies.

**Comment by lroeser** [comment]
I have added "ogit:contains" for BidAdjustmentGroup and left ogit:consistsOf as suggested by you.
Regarding "ogit:uses" for Advertising:BidAdjustment: This was a copy-paste error to begin with. Actually, the requirement specifies "ogit:consistsOf". This edge is not in used by now (and was never), otherwise this error would have popped up already.

**Comment by KaushikGondaliya** [comment]
"validationtest" job had an issue because SDF validator was broken. It is fixed now… But job needs to be retriggered either by reopening pull request/ if there is new commit.

**Comment by lroeser** [comment]
https://github.com/arago/OGIT/pull/619

**Pull request closed without merging**
